/* SPDX-License-Identifier: GPL-2.0-only */
/*
 * LowRISC Sonata memory layout constants.
 */
#ifndef _ASM_RISCV_SONATA_H
#define _ASM_RISCV_SONATA_H

#ifdef __ASSEMBLY__
#define SONATA_SRAM_BASE	0x00100000
#define SONATA_SRAM_END		0x00120000
#define SONATA_HYPERRAM_BASE	0x40000000
#define SONATA_HYPERRAM_SIZE	0x00800000
#define SONATA_HYPERRAM_END	(SONATA_HYPERRAM_BASE + SONATA_HYPERRAM_SIZE)
#define SONATA_HYPERRAM_STACK_SIZE	0x00001000
#define SONATA_HYPERRAM_STACK_BASE	(SONATA_HYPERRAM_END - SONATA_HYPERRAM_STACK_SIZE)
#else
#define SONATA_SRAM_BASE	0x00100000UL
#define SONATA_SRAM_END		0x00120000UL
#define SONATA_HYPERRAM_BASE	0x40000000UL
#define SONATA_HYPERRAM_SIZE	0x00800000UL
#define SONATA_HYPERRAM_END	(SONATA_HYPERRAM_BASE + SONATA_HYPERRAM_SIZE)
#define SONATA_HYPERRAM_STACK_SIZE	0x00001000UL
#define SONATA_HYPERRAM_STACK_BASE	(SONATA_HYPERRAM_END - SONATA_HYPERRAM_STACK_SIZE)
#endif

#ifndef __ASSEMBLY__
unsigned long riscv_sonata_prepare_stack_switch(void);
void riscv_sonata_stack_switch_finish(unsigned long new_base);
#endif

#endif /* _ASM_RISCV_SONATA_H */
